/**
 * Signification des 114 sourates : traduction du nom + thème en une phrase,
 * en français ET en anglais. Affiché sous le nom dans « Lecture libre » pour
 * situer la sourate d'un coup d'œil (ex. Al-Munafiqun → « Les Hypocrites » —
 * dénonce ceux qui feignent la foi).
 *
 * ⚠️ CONTENU RELIGIEUX — à faire relire : ces résumés sont volontairement très
 * courts et ne remplacent pas un tafsir. Indexé par numéro de sourate (1–114).
 */
type Meaning = { fr: string; en: string };

export const SOURATE_MEANING: Record<number, Meaning> = {
  1: { fr: '« L\'Ouverture » — la prière d\'ouverture, louange et demande de guidance.', en: '"The Opening" — the opening prayer: praise and a plea for guidance.' },
  2: { fr: '« La Vache » — la plus longue sourate : loi, foi et récit de la vache des Enfants d\'Israël.', en: '"The Cow" — the longest surah: law, faith, and the story of the Israelites\' cow.' },
  3: { fr: '« La Famille d\'Imran » — la foi, Marie, Jésus et l\'unité des croyants.', en: '"The Family of Imran" — faith, Mary, Jesus, and the unity of believers.' },
  4: { fr: '« Les Femmes » — droits des femmes, héritage, mariage et justice sociale.', en: '"The Women" — women\'s rights, inheritance, marriage, and social justice.' },
  5: { fr: '« La Table servie » — pactes, licite et illicite, la table demandée par les apôtres.', en: '"The Table Spread" — covenants, lawful and unlawful, and the apostles\' requested table.' },
  6: { fr: '« Les Bestiaux » — l\'unicité de Dieu et réfutation des croyances polythéistes.', en: '"The Cattle" — God\'s oneness and a refutation of polytheistic beliefs.' },
  7: { fr: '« Al-A\'raf (les Murailles) » — les prophètes, Adam, et les gens des hauteurs entre paradis et enfer.', en: '"The Heights" — the prophets, Adam, and those on the heights between Paradise and Hell.' },
  8: { fr: '« Le Butin » — la bataille de Badr et les règles du butin de guerre.', en: '"The Spoils of War" — the Battle of Badr and the rules of war spoils.' },
  9: { fr: '« Le Repentir » — rupture des pactes avec les polythéistes et dénonciation des hypocrites.', en: '"The Repentance" — breaking pacts with polytheists and exposing the hypocrites.' },
  10: { fr: '« Jonas » — l\'unicité de Dieu et le sort des peuples qui démentirent leurs prophètes.', en: '"Jonah" — God\'s oneness and the fate of peoples who denied their prophets.' },
  11: { fr: '« Houd » — les prophètes Houd, Salih, Noé et Loth face à leurs peuples.', en: '"Hud" — the prophets Hud, Salih, Noah, and Lot before their peoples.' },
  12: { fr: '« Joseph » — le récit complet et détaillé du prophète Joseph et de ses frères.', en: '"Joseph" — the complete, detailed story of the prophet Joseph and his brothers.' },
  13: { fr: '« Le Tonnerre » — les signes de Dieu dans la création et la vérité de la révélation.', en: '"The Thunder" — God\'s signs in creation and the truth of the revelation.' },
  14: { fr: '« Abraham » — la gratitude, l\'invocation d\'Abraham et le sort des ingrats.', en: '"Abraham" — gratitude, Abraham\'s supplication, and the fate of the ungrateful.' },
  15: { fr: '« Al-Hijr » — les gens d\'Al-Hijr et la protection du Coran par Dieu.', en: '"Al-Hijr" — the people of Al-Hijr and God\'s protection of the Quran.' },
  16: { fr: '« Les Abeilles » — les innombrables bienfaits de Dieu dans la création.', en: '"The Bee" — the countless blessings of God in creation.' },
  17: { fr: '« Le Voyage nocturne » — l\'Isra du Prophète et les commandements moraux.', en: '"The Night Journey" — the Prophet\'s Isra and the moral commandments.' },
  18: { fr: '« La Caverne » — les gens de la caverne, Moïse et Al-Khidr, Dhul-Qarnayn.', en: '"The Cave" — the people of the cave, Moses and Al-Khidr, and Dhul-Qarnayn.' },
  19: { fr: '« Marie » — la naissance de Jésus et l\'histoire de plusieurs prophètes.', en: '"Mary" — the birth of Jesus and the stories of several prophets.' },
  20: { fr: '« Ta-Ha » — l\'histoire détaillée de Moïse face à Pharaon.', en: '"Ta-Ha" — the detailed story of Moses before Pharaoh.' },
  21: { fr: '« Les Prophètes » — un panorama des prophètes et de leur message d\'unicité.', en: '"The Prophets" — an overview of the prophets and their message of oneness.' },
  22: { fr: '« Le Pèlerinage » — les rites du Hajj et la résurrection.', en: '"The Pilgrimage" — the rites of Hajj and the resurrection.' },
  23: { fr: '« Les Croyants » — les qualités des vrais croyants et la promesse du succès.', en: '"The Believers" — the qualities of true believers and the promise of success.' },
  24: { fr: '« La Lumière » — la pudeur, la chasteté et le verset de la Lumière de Dieu.', en: '"The Light" — modesty, chastity, and the Verse of God\'s Light.' },
  25: { fr: '« Le Discernement » — le Coran comme critère entre le vrai et le faux.', en: '"The Criterion" — the Quran as the standard between truth and falsehood.' },
  26: { fr: '« Les Poètes » — les récits des prophètes et le rejet des mensonges des poètes.', en: '"The Poets" — the stories of the prophets and the rejection of poets\' falsehoods.' },
  27: { fr: '« Les Fourmis » — Salomon, la reine de Saba et la fourmi.', en: '"The Ant" — Solomon, the Queen of Sheba, and the ant.' },
  28: { fr: '« Le Récit » — l\'histoire de Moïse depuis sa naissance jusqu\'à sa mission.', en: '"The Stories" — Moses\' life from his birth to his mission.' },
  29: { fr: '« L\'Araignée » — l\'épreuve de la foi, fragile comme la toile pour qui s\'y fie sans Dieu.', en: '"The Spider" — the test of faith, as frail as a web for those who rely on other than God.' },
  30: { fr: '« Les Romains » — la victoire annoncée des Byzantins et les signes de Dieu.', en: '"The Romans" — the foretold victory of the Byzantines and the signs of God.' },
  31: { fr: '« Luqman » — les sages conseils de Luqman à son fils.', en: '"Luqman" — the wise advice of Luqman to his son.' },
  32: { fr: '« La Prosternation » — la création, la résurrection et l\'humilité devant Dieu.', en: '"The Prostration" — creation, resurrection, and humility before God.' },
  33: { fr: '« Les Coalisés » — la bataille du Fossé et les règles de la vie du Prophète.', en: '"The Combined Forces" — the Battle of the Trench and rules of the Prophet\'s life.' },
  34: { fr: '« Saba » — le peuple de Saba, la gratitude et l\'ingratitude.', en: '"Sheba" — the people of Sheba, gratitude, and ingratitude.' },
  35: { fr: '« Le Créateur » — la puissance créatrice de Dieu et Ses anges.', en: '"The Originator" — God\'s creative power and His angels.' },
  36: { fr: '« Ya-Sin » — le « cœur du Coran » : l\'unicité, la prophétie et la résurrection.', en: '"Ya-Sin" — the "heart of the Quran": oneness, prophethood, and resurrection.' },
  37: { fr: '« Les Rangés » — les anges rangés et les récits des prophètes, dont le sacrifice d\'Abraham.', en: '"Those Ranged in Ranks" — the ranged angels and the prophets\' stories, including Abraham\'s sacrifice.' },
  38: { fr: '« Sad » — David, Salomon, Job et la dispute d\'Iblis.', en: '"Sad" — David, Solomon, Job, and the defiance of Iblis.' },
  39: { fr: '« Les Groupes » — la sincérité du culte et le sort des croyants et mécréants.', en: '"The Groups" — sincerity of worship and the fate of believers and disbelievers.' },
  40: { fr: '« Le Pardonneur » — un croyant de la famille de Pharaon défend Moïse.', en: '"The Forgiver" — a believer from Pharaoh\'s household defends Moses.' },
  41: { fr: '« Les Versets détaillés » — le Coran clair et la réponse à ceux qui s\'en détournent.', en: '"Explained in Detail" — the clear Quran and the answer to those who turn away.' },
  42: { fr: '« La Consultation » — la concertation entre croyants et l\'unité du message divin.', en: '"The Consultation" — mutual counsel among believers and the unity of the divine message.' },
  43: { fr: '« L\'Ornement » — les fausses valeurs de ce monde et la vérité de la révélation.', en: '"The Ornaments of Gold" — the false values of this world and the truth of the revelation.' },
  44: { fr: '« La Fumée » — un signe annonciateur du châtiment et la nuit bénie.', en: '"The Smoke" — a sign foretelling punishment and the blessed night.' },
  45: { fr: '« L\'Agenouillée » — chaque communauté agenouillée devant son livre au Jugement.', en: '"The Kneeling" — every community kneeling before its record on Judgement Day.' },
  46: { fr: '« Al-Ahqaf (les Dunes) » — le peuple de Houd et la foi des djinns.', en: '"The Sand Dunes" — the people of Hud and the faith of the jinn.' },
  47: { fr: '« Muhammad » — le combat, la fermeté des croyants et la ruine des mécréants.', en: '"Muhammad" — struggle, the steadfastness of believers, and the ruin of disbelievers.' },
  48: { fr: '« La Victoire éclatante » — le traité de Hudaybiyya annoncé comme une victoire.', en: '"The Victory" — the Treaty of Hudaybiyya foretold as a victory.' },
  49: { fr: '« Les Appartements » — l\'éthique sociale : fraternité, respect et refus de la médisance.', en: '"The Chambers" — social ethics: brotherhood, respect, and refusing slander.' },
  50: { fr: '« Qaf » — la résurrection et la proximité de Dieu envers l\'homme.', en: '"Qaf" — the resurrection and God\'s closeness to humankind.' },
  51: { fr: '« Qui éparpillent » — les vents disperseurs, signes de la providence divine.', en: '"The Winnowing Winds" — the scattering winds as signs of divine providence.' },
  52: { fr: '« At-Tur (le Mont) » — le serment par le Mont et la réalité du Jugement.', en: '"The Mount" — the oath by the Mount and the reality of Judgement.' },
  53: { fr: '« L\'Étoile » — l\'ascension du Prophète et la vérité de la révélation.', en: '"The Star" — the Prophet\'s ascension and the truth of the revelation.' },
  54: { fr: '« La Lune » — le fendillement de la lune et le sort des peuples démentisseurs.', en: '"The Moon" — the splitting of the moon and the fate of denying peoples.' },
  55: { fr: '« Le Tout Miséricordieux » — l\'énumération des bienfaits de Dieu, avec un refrain répété.', en: '"The Most Merciful" — an enumeration of God\'s blessings, with a repeated refrain.' },
  56: { fr: '« L\'Événement » — la description du Jour du Jugement et des trois groupes d\'humains.', en: '"The Inevitable Event" — the Day of Judgement and the three groups of people.' },
  57: { fr: '« Le Fer » — la puissance de Dieu et l\'appel à la dépense dans Son sentier.', en: '"The Iron" — God\'s might and the call to spend in His path.' },
  58: { fr: '« La Discussion » — la femme qui plaide auprès du Prophète et la justice de Dieu.', en: '"The Pleading Woman" — the woman who pleads with the Prophet and God\'s justice.' },
  59: { fr: '« L\'Exode » — l\'expulsion des Banu Nadir et les beaux noms de Dieu.', en: '"The Exile" — the expulsion of the Banu Nadir and the beautiful names of God.' },
  60: { fr: '« L\'Éprouvée » — les rapports avec les non-musulmans et la loyauté.', en: '"The Woman to be Examined" — relations with non-Muslims and loyalty.' },
  61: { fr: '« Le Rang » — l\'appel au combat en rangs serrés dans le sentier de Dieu.', en: '"The Ranks" — the call to fight in solid ranks in God\'s path.' },
  62: { fr: '« Le Vendredi » — la prière du vendredi et le rappel du savoir.', en: '"The Congregation, Friday" — the Friday prayer and the reminder of knowledge.' },
  63: { fr: '« Les Hypocrites » — dénonce ceux qui feignent la foi tout en la trahissant.', en: '"The Hypocrites" — exposes those who feign faith while betraying it.' },
  64: { fr: '« La Grande Perte mutuelle » — le Jour où se révèlent gains et pertes de chacun.', en: '"The Mutual Loss and Gain" — the Day when everyone\'s gains and losses are revealed.' },
  65: { fr: '« Le Divorce » — les règles du divorce et le respect des délais.', en: '"The Divorce" — the rules of divorce and observing the waiting periods.' },
  66: { fr: '« L\'Interdiction » — un épisode familial du Prophète et l\'appel au repentir.', en: '"The Prohibition" — a household episode of the Prophet and the call to repent.' },
  67: { fr: '« La Royauté » — la souveraineté de Dieu sur la vie et la mort.', en: '"The Dominion" — God\'s sovereignty over life and death.' },
  68: { fr: '« La Plume » — défense du caractère du Prophète et parabole des propriétaires du verger.', en: '"The Pen" — a defense of the Prophet\'s character and the parable of the garden owners.' },
  69: { fr: '« Celle qui montre la vérité » — la réalité inéluctable du Jugement.', en: '"The Reality" — the inevitable reality of Judgement.' },
  70: { fr: '« Les Voies d\'ascension » — la patience face au châtiment et les degrés vers Dieu.', en: '"The Ascending Stairways" — patience before punishment and the degrees toward God.' },
  71: { fr: '« Noé » — la prédication persévérante de Noé face à son peuple.', en: '"Noah" — Noah\'s persevering call to his people.' },
  72: { fr: '« Les Djinns » — un groupe de djinns qui écoutent le Coran et croient.', en: '"The Jinn" — a group of jinn who hear the Quran and believe.' },
  73: { fr: '« L\'Enveloppé » — l\'appel à la prière de nuit adressé au Prophète.', en: '"The Enshrouded One" — the call to night prayer addressed to the Prophet.' },
  74: { fr: '« Le Revêtu d\'un manteau » — l\'ordre d\'avertir et le châtiment des orgueilleux.', en: '"The Cloaked One" — the command to warn and the punishment of the arrogant.' },
  75: { fr: '« La Résurrection » — la certitude du relèvement des morts.', en: '"The Resurrection" — the certainty of the raising of the dead.' },
  76: { fr: '« L\'Homme » — la création de l\'homme et la récompense des pieux.', en: '"Man" — the creation of man and the reward of the righteous.' },
  77: { fr: '« Les Envoyés » — les vents envoyés et les menaces du Jour du Jugement.', en: '"The Emissaries" — the sent winds and the warnings of Judgement Day.' },
  78: { fr: '« La Nouvelle » — la grande nouvelle de la résurrection.', en: '"The Great News" — the momentous news of the resurrection.' },
  79: { fr: '« Les Anges arracheurs » — les anges qui arrachent les âmes et le Jugement.', en: '"Those Who Pull Out" — the angels who draw out souls, and the Judgement.' },
  80: { fr: '« Il s\'est renfrogné » — le reproche doux au Prophète au sujet de l\'aveugle.', en: '"He Frowned" — the gentle reproach to the Prophet regarding the blind man.' },
  81: { fr: '« L\'Obscurcissement » — les bouleversements cosmiques du Dernier Jour.', en: '"The Overthrowing" — the cosmic upheavals of the Last Day.' },
  82: { fr: '« La Rupture » — le ciel qui se fend et le bilan des actes.', en: '"The Cleaving" — the splitting of the sky and the reckoning of deeds.' },
  83: { fr: '« Les Fraudeurs » — la condamnation de ceux qui trichent dans la mesure.', en: '"The Defrauders" — the condemnation of those who cheat in measure.' },
  84: { fr: '« La Déchirure » — le ciel déchiré et la remise du livre des actes.', en: '"The Splitting Open" — the torn sky and the handing out of the record of deeds.' },
  85: { fr: '« Les Constellations » — les gens du Fossé et la fermeté des croyants persécutés.', en: '"The Constellations" — the people of the ditch and the steadfastness of persecuted believers.' },
  86: { fr: '« L\'Astre nocturne » — l\'astre perçant et la surveillance de chaque âme.', en: '"The Nightcomer" — the piercing star and the watch kept over every soul.' },
  87: { fr: '« Le Très-Haut » — la glorification de Dieu et la simplicité du rappel.', en: '"The Most High" — the glorification of God and the ease of the reminder.' },
  88: { fr: '« L\'Enveloppante » — le Jour qui enveloppe tout et le contraste des destins.', en: '"The Overwhelming" — the all-enveloping Day and the contrast of destinies.' },
  89: { fr: '« L\'Aube » — le serment par l\'aube et le sort des peuples tyranniques.', en: '"The Dawn" — the oath by the dawn and the fate of tyrannical peoples.' },
  90: { fr: '« La Cité » — La Mecque, l\'effort de l\'homme et les voies du bien.', en: '"The City" — Mecca, human striving, and the paths of goodness.' },
  91: { fr: '« Le Soleil » — le serment par le soleil et la purification de l\'âme.', en: '"The Sun" — the oath by the sun and the purification of the soul.' },
  92: { fr: '« La Nuit » — le contraste entre le généreux pieux et l\'avare.', en: '"The Night" — the contrast between the generous, God-fearing and the miserly.' },
  93: { fr: '« Le Jour montant » — le réconfort du Prophète : Dieu ne t\'a pas abandonné.', en: '"The Morning Brightness" — comfort for the Prophet: God has not forsaken you.' },
  94: { fr: '« L\'Ouverture (de la poitrine) » — l\'apaisement du Prophète : après la difficulté vient la facilité.', en: '"The Relief" — reassurance for the Prophet: with hardship comes ease.' },
  95: { fr: '« Le Figuier » — la noblesse originelle de l\'homme et sa chute possible.', en: '"The Fig" — the original nobility of man and his possible fall.' },
  96: { fr: '« L\'Adhérence » — les tout premiers versets révélés : « Lis ! ».', en: '"The Clinging Clot" — the very first revealed verses: "Read!".' },
  97: { fr: '« La Destinée » — la nuit du Destin, meilleure que mille mois.', en: '"The Power" — the Night of Decree, better than a thousand months.' },
  98: { fr: '« La Preuve évidente » — la clarté du message face aux gens du Livre.', en: '"The Clear Proof" — the clarity of the message before the People of the Book.' },
  99: { fr: '« La Secousse » — le tremblement final de la terre et le bilan des atomes de bien et de mal.', en: '"The Earthquake" — the earth\'s final quake and the reckoning of every atom of good and evil.' },
  100: { fr: '« Les Coursiers » — les chevaux de guerre et l\'ingratitude de l\'homme.', en: '"The Racers" — the war horses and the ingratitude of man.' },
  101: { fr: '« Le Fracas » — le cataclysme du Jugement et la pesée des œuvres.', en: '"The Calamity" — the cataclysm of Judgement and the weighing of deeds.' },
  102: { fr: '« La Course aux richesses » — l\'accumulation qui détourne de l\'essentiel.', en: '"The Rivalry in Worldly Increase" — the hoarding that distracts from what matters.' },
  103: { fr: '« Le Temps » — l\'homme est en perdition, sauf les croyants vertueux.', en: '"The Declining Day" — humanity is in loss, except the righteous believers.' },
  104: { fr: '« Les Calomniateurs » — la condamnation de la médisance et de la cupidité.', en: '"The Slanderer" — the condemnation of backbiting and greed.' },
  105: { fr: '« L\'Éléphant » — la déroute de l\'armée d\'Abraha venue détruire la Kaaba.', en: '"The Elephant" — the rout of Abraha\'s army that came to destroy the Kaaba.' },
  106: { fr: '« Quraysh » — le rappel des bienfaits accordés à la tribu de Quraysh.', en: '"Quraysh" — the reminder of the blessings granted to the Quraysh tribe.' },
  107: { fr: '« L\'Ustensile » — la dénonciation de qui néglige la prière et le partage.', en: '"The Small Kindnesses" — condemning those who neglect prayer and sharing.' },
  108: { fr: '« L\'Abondance » — le don de l\'abondance (Al-Kawthar) accordé au Prophète.', en: '"The Abundance" — the gift of abundance (Al-Kawthar) granted to the Prophet.' },
  109: { fr: '« Les Mécréants » — la nette séparation des voies : « À vous votre religion, à moi la mienne ».', en: '"The Disbelievers" — the clear parting of ways: "To you your religion, to me mine".' },
  110: { fr: '« Les Secours » — l\'annonce de la victoire et l\'entrée des gens dans la religion.', en: '"The Divine Support" — the announcement of victory and people entering the faith.' },
  111: { fr: '« Les Fibres » — la condamnation d\'Abou Lahab, oncle hostile du Prophète.', en: '"The Palm Fiber" — the condemnation of Abu Lahab, the Prophet\'s hostile uncle.' },
  112: { fr: '« Le Monothéisme pur » — la définition de l\'unicité absolue de Dieu.', en: '"The Sincerity" — the definition of God\'s absolute oneness.' },
  113: { fr: '« L\'Aube naissante » — la recherche de protection contre les maux de la création.', en: '"The Daybreak" — seeking refuge from the evils of creation.' },
  114: { fr: '« Les Hommes » — la recherche de protection contre le mal du tentateur.', en: '"Mankind" — seeking refuge from the evil of the whisperer.' },
};

/** Signification d'une sourate dans la langue voulue (fr par défaut si l'anglais manque). */
export function sourateMeaning(numero: number, lang: 'fr' | 'en' | 'ar'): string | null {
  const m = SOURATE_MEANING[numero];
  if (!m) return null;
  return lang === 'en' ? m.en : m.fr;
}
