// ─── Les 99 noms d'Allah (Asmā' ul-Ḥusnā) — copie Swift ────────────────────
// Généré depuis constants/asmaulHusna.ts (source de vérité, TS) — garder les
// deux fichiers synchronisés si le contenu religieux est corrigé ou complété.
// ⚠️ CONTENU RELIGIEUX — voir le fichier TS pour la note de relecture.

struct AsmaName {
    let numero: Int
    let arabe: String
    let translitteration: String
    let fr: String
}

let ASMA_UL_HUSNA: [AsmaName] = [
    AsmaName(numero: 1, arabe: "ٱلرَّحْمَٰن", translitteration: "Ar-Rahmān", fr: "Le Tout Miséricordieux"),
    AsmaName(numero: 2, arabe: "ٱلرَّحِيم", translitteration: "Ar-Rahīm", fr: "Le Très Miséricordieux"),
    AsmaName(numero: 3, arabe: "ٱلْمَلِك", translitteration: "Al-Malik", fr: "Le Souverain"),
    AsmaName(numero: 4, arabe: "ٱلْقُدُّوس", translitteration: "Al-Quddūs", fr: "Le Pur"),
    AsmaName(numero: 5, arabe: "ٱلسَّلَام", translitteration: "As-Salām", fr: "La Paix"),
    AsmaName(numero: 6, arabe: "ٱلْمُؤْمِن", translitteration: "Al-Mu'min", fr: "Le Rassurant"),
    AsmaName(numero: 7, arabe: "ٱلْمُهَيْمِن", translitteration: "Al-Muhaymin", fr: "Le Gardien"),
    AsmaName(numero: 8, arabe: "ٱلْعَزِيز", translitteration: "Al-'Azīz", fr: "Le Tout-Puissant"),
    AsmaName(numero: 9, arabe: "ٱلْجَبَّار", translitteration: "Al-Jabbār", fr: "Le Contraignant"),
    AsmaName(numero: 10, arabe: "ٱلْمُتَكَبِّر", translitteration: "Al-Mutakabbir", fr: "Le Suprême"),
    AsmaName(numero: 11, arabe: "ٱلْخَالِق", translitteration: "Al-Khāliq", fr: "Le Créateur"),
    AsmaName(numero: 12, arabe: "ٱلْبَارِئ", translitteration: "Al-Bāri'", fr: "Le Producteur"),
    AsmaName(numero: 13, arabe: "ٱلْمُصَوِّر", translitteration: "Al-Musawwir", fr: "Le Formateur"),
    AsmaName(numero: 14, arabe: "ٱلْغَفَّار", translitteration: "Al-Ghaffār", fr: "Le Grand Pardonneur"),
    AsmaName(numero: 15, arabe: "ٱلْقَهَّار", translitteration: "Al-Qahhār", fr: "Le Dominateur"),
    AsmaName(numero: 16, arabe: "ٱلْوَهَّاب", translitteration: "Al-Wahhāb", fr: "Le Donateur"),
    AsmaName(numero: 17, arabe: "ٱلرَّزَّاق", translitteration: "Ar-Razzāq", fr: "Le Pourvoyeur"),
    AsmaName(numero: 18, arabe: "ٱلْفَتَّاح", translitteration: "Al-Fattāh", fr: "Celui qui ouvre"),
    AsmaName(numero: 19, arabe: "ٱلْعَلِيم", translitteration: "Al-'Alīm", fr: "L'Omniscient"),
    AsmaName(numero: 20, arabe: "ٱلْقَابِض", translitteration: "Al-Qābid", fr: "Celui qui restreint"),
    AsmaName(numero: 21, arabe: "ٱلْبَاسِط", translitteration: "Al-Bāsit", fr: "Celui qui étend"),
    AsmaName(numero: 22, arabe: "ٱلْخَافِض", translitteration: "Al-Khāfid", fr: "Celui qui abaisse"),
    AsmaName(numero: 23, arabe: "ٱلرَّافِع", translitteration: "Ar-Rāfi'", fr: "Celui qui élève"),
    AsmaName(numero: 24, arabe: "ٱلْمُعِزّ", translitteration: "Al-Mu'izz", fr: "Celui qui honore"),
    AsmaName(numero: 25, arabe: "ٱلْمُذِلّ", translitteration: "Al-Mudhill", fr: "Celui qui humilie"),
    AsmaName(numero: 26, arabe: "ٱلسَّمِيع", translitteration: "As-Samī'", fr: "Celui qui entend tout"),
    AsmaName(numero: 27, arabe: "ٱلْبَصِير", translitteration: "Al-Basīr", fr: "Celui qui voit tout"),
    AsmaName(numero: 28, arabe: "ٱلْحَكَم", translitteration: "Al-Hakam", fr: "Le Juge"),
    AsmaName(numero: 29, arabe: "ٱلْعَدْل", translitteration: "Al-'Adl", fr: "Le Juste"),
    AsmaName(numero: 30, arabe: "ٱللَّطِيف", translitteration: "Al-Latīf", fr: "Le Subtil"),
    AsmaName(numero: 31, arabe: "ٱلْخَبِير", translitteration: "Al-Khabīr", fr: "Le Parfaitement Informé"),
    AsmaName(numero: 32, arabe: "ٱلْحَلِيم", translitteration: "Al-Halīm", fr: "Le Longanime"),
    AsmaName(numero: 33, arabe: "ٱلْعَظِيم", translitteration: "Al-'Azīm", fr: "Le Magnifique"),
    AsmaName(numero: 34, arabe: "ٱلْغَفُور", translitteration: "Al-Ghafūr", fr: "Le Pardonneur"),
    AsmaName(numero: 35, arabe: "ٱلشَّكُور", translitteration: "Ash-Shakūr", fr: "Le Reconnaissant"),
    AsmaName(numero: 36, arabe: "ٱلْعَلِيّ", translitteration: "Al-'Alī", fr: "Le Très-Haut"),
    AsmaName(numero: 37, arabe: "ٱلْكَبِير", translitteration: "Al-Kabīr", fr: "Le Grand"),
    AsmaName(numero: 38, arabe: "ٱلْحَفِيظ", translitteration: "Al-Hafīz", fr: "Le Gardien"),
    AsmaName(numero: 39, arabe: "ٱلْمُقِيت", translitteration: "Al-Muqīt", fr: "Le Nourricier"),
    AsmaName(numero: 40, arabe: "ٱلْحَسِيب", translitteration: "Al-Hasīb", fr: "Celui qui suffit"),
    AsmaName(numero: 41, arabe: "ٱلْجَلِيل", translitteration: "Al-Jalīl", fr: "Le Majestueux"),
    AsmaName(numero: 42, arabe: "ٱلْكَرِيم", translitteration: "Al-Karīm", fr: "Le Généreux"),
    AsmaName(numero: 43, arabe: "ٱلرَّقِيب", translitteration: "Ar-Raqīb", fr: "Le Vigilant"),
    AsmaName(numero: 44, arabe: "ٱلْمُجِيب", translitteration: "Al-Mujīb", fr: "Celui qui exauce"),
    AsmaName(numero: 45, arabe: "ٱلْوَاسِع", translitteration: "Al-Wāsi'", fr: "L'Immense"),
    AsmaName(numero: 46, arabe: "ٱلْحَكِيم", translitteration: "Al-Hakīm", fr: "Le Sage"),
    AsmaName(numero: 47, arabe: "ٱلْوَدُود", translitteration: "Al-Wadūd", fr: "L'Aimant"),
    AsmaName(numero: 48, arabe: "ٱلْمَجِيد", translitteration: "Al-Majīd", fr: "Le Glorieux"),
    AsmaName(numero: 49, arabe: "ٱلْبَاعِث", translitteration: "Al-Bā'ith", fr: "Celui qui ressuscite"),
    AsmaName(numero: 50, arabe: "ٱلشَّهِيد", translitteration: "Ash-Shahīd", fr: "Le Témoin"),
    AsmaName(numero: 51, arabe: "ٱلْحَقّ", translitteration: "Al-Haqq", fr: "La Vérité"),
    AsmaName(numero: 52, arabe: "ٱلْوَكِيل", translitteration: "Al-Wakīl", fr: "Le Garant"),
    AsmaName(numero: 53, arabe: "ٱلْقَوِيّ", translitteration: "Al-Qawī", fr: "Le Fort"),
    AsmaName(numero: 54, arabe: "ٱلْمَتِين", translitteration: "Al-Matīn", fr: "L'Inébranlable"),
    AsmaName(numero: 55, arabe: "ٱلْوَلِيّ", translitteration: "Al-Walī", fr: "Le Protecteur"),
    AsmaName(numero: 56, arabe: "ٱلْحَمِيد", translitteration: "Al-Hamīd", fr: "Le Digne de louange"),
    AsmaName(numero: 57, arabe: "ٱلْمُحْصِي", translitteration: "Al-Muhsī", fr: "Celui qui dénombre"),
    AsmaName(numero: 58, arabe: "ٱلْمُبْدِئ", translitteration: "Al-Mubdi'", fr: "Celui qui initie"),
    AsmaName(numero: 59, arabe: "ٱلْمُعِيد", translitteration: "Al-Mu'īd", fr: "Celui qui recommence"),
    AsmaName(numero: 60, arabe: "ٱلْمُحْيِي", translitteration: "Al-Muhyī", fr: "Celui qui donne la vie"),
    AsmaName(numero: 61, arabe: "ٱلْمُمِيت", translitteration: "Al-Mumīt", fr: "Celui qui donne la mort"),
    AsmaName(numero: 62, arabe: "ٱلْحَيّ", translitteration: "Al-Hayy", fr: "Le Vivant"),
    AsmaName(numero: 63, arabe: "ٱلْقَيُّوم", translitteration: "Al-Qayyūm", fr: "Le Subsistant par Soi"),
    AsmaName(numero: 64, arabe: "ٱلْوَاجِد", translitteration: "Al-Wājid", fr: "Celui qui trouve"),
    AsmaName(numero: 65, arabe: "ٱلْمَاجِد", translitteration: "Al-Mājid", fr: "Le Noble"),
    AsmaName(numero: 66, arabe: "ٱلْوَاحِد", translitteration: "Al-Wāhid", fr: "L'Unique"),
    AsmaName(numero: 67, arabe: "ٱلْأَحَد", translitteration: "Al-Ahad", fr: "L'Un"),
    AsmaName(numero: 68, arabe: "ٱلصَّمَد", translitteration: "As-Samad", fr: "Le Soutien universel"),
    AsmaName(numero: 69, arabe: "ٱلْقَادِر", translitteration: "Al-Qādir", fr: "Le Puissant"),
    AsmaName(numero: 70, arabe: "ٱلْمُقْتَدِر", translitteration: "Al-Muqtadir", fr: "Le Tout-Déterminant"),
    AsmaName(numero: 71, arabe: "ٱلْمُقَدِّم", translitteration: "Al-Muqaddim", fr: "Celui qui avance"),
    AsmaName(numero: 72, arabe: "ٱلْمُؤَخِّر", translitteration: "Al-Mu'akhkhir", fr: "Celui qui recule"),
    AsmaName(numero: 73, arabe: "ٱلْأَوَّل", translitteration: "Al-Awwal", fr: "Le Premier"),
    AsmaName(numero: 74, arabe: "ٱلْآخِر", translitteration: "Al-Ākhir", fr: "Le Dernier"),
    AsmaName(numero: 75, arabe: "ٱلظَّاهِر", translitteration: "Az-Zāhir", fr: "L'Apparent"),
    AsmaName(numero: 76, arabe: "ٱلْبَاطِن", translitteration: "Al-Bātin", fr: "Le Caché"),
    AsmaName(numero: 77, arabe: "ٱلْوَالِي", translitteration: "Al-Wālī", fr: "Le Maître"),
    AsmaName(numero: 78, arabe: "ٱلْمُتَعَالِي", translitteration: "Al-Muta'ālī", fr: "Le Sublime"),
    AsmaName(numero: 79, arabe: "ٱلْبَرّ", translitteration: "Al-Barr", fr: "Le Bienfaisant"),
    AsmaName(numero: 80, arabe: "ٱلتَّوَّاب", translitteration: "At-Tawwāb", fr: "Celui qui accueille le repentir"),
    AsmaName(numero: 81, arabe: "ٱلْمُنْتَقِم", translitteration: "Al-Muntaqim", fr: "Le Vengeur"),
    AsmaName(numero: 82, arabe: "ٱلْعَفُوّ", translitteration: "Al-'Afū", fr: "Celui qui efface"),
    AsmaName(numero: 83, arabe: "ٱلرَّؤُوف", translitteration: "Ar-Ra'ūf", fr: "Le Compatissant"),
    AsmaName(numero: 84, arabe: "مَالِكُ ٱلْمُلْك", translitteration: "Mālik-ul-Mulk", fr: "Le Roi de la royauté"),
    AsmaName(numero: 85, arabe: "ذُو ٱلْجَلَالِ وَٱلْإِكْرَام", translitteration: "Dhul-Jalāli wal-Ikrām", fr: "Le Détenteur de la majesté et de la générosité"),
    AsmaName(numero: 86, arabe: "ٱلْمُقْسِط", translitteration: "Al-Muqsit", fr: "L'Équitable"),
    AsmaName(numero: 87, arabe: "ٱلْجَامِع", translitteration: "Al-Jāmi'", fr: "Celui qui rassemble"),
    AsmaName(numero: 88, arabe: "ٱلْغَنِيّ", translitteration: "Al-Ghanī", fr: "Celui qui se suffit à Lui-même"),
    AsmaName(numero: 89, arabe: "ٱلْمُغْنِي", translitteration: "Al-Mughnī", fr: "Celui qui enrichit"),
    AsmaName(numero: 90, arabe: "ٱلْمَانِع", translitteration: "Al-Māni'", fr: "Celui qui empêche"),
    AsmaName(numero: 91, arabe: "ٱلضَّارّ", translitteration: "Ad-Dārr", fr: "Celui qui peut nuire"),
    AsmaName(numero: 92, arabe: "ٱلنَّافِع", translitteration: "An-Nāfi'", fr: "Celui qui est utile"),
    AsmaName(numero: 93, arabe: "ٱلنُّور", translitteration: "An-Nūr", fr: "La Lumière"),
    AsmaName(numero: 94, arabe: "ٱلْهَادِي", translitteration: "Al-Hādī", fr: "Le Guide"),
    AsmaName(numero: 95, arabe: "ٱلْبَدِيع", translitteration: "Al-Badī'", fr: "Le Novateur"),
    AsmaName(numero: 96, arabe: "ٱلْبَاقِي", translitteration: "Al-Bāqī", fr: "Le Permanent"),
    AsmaName(numero: 97, arabe: "ٱلْوَارِث", translitteration: "Al-Wārith", fr: "L'Héritier"),
    AsmaName(numero: 98, arabe: "ٱلرَّشِيد", translitteration: "Ar-Rashīd", fr: "Le Guide vers le bien"),
    AsmaName(numero: 99, arabe: "ٱلصَّبُور", translitteration: "As-Sabūr", fr: "Le Patient"),
]
